apiVersion: v1
name: mongodb-backup
version: 1.0.0
appVersion: 1.0.0
type: application
keywords:
  - "mongodb"
  - "backup"
description: Backup the mongodb and compress it to tarball and copy it to OCI OS bucket